name: testing_app
description: A sample that shows testing in Flutter.

version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  provider: ^6.0.2
  go_router: ">=10.0.0 <14.0.0"

dev_dependencies:
  analysis_defaults:
    path: analysis_defaults
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.16.8

flutter:
  fonts:
    - family: Sixtyfour
      fonts:
        - asset: fonts/Sixtyfour-Regular.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Break
      fonts:
        - asset: fonts/Break.ttf
    - family: Bebas
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: Payback
      fonts:
        - asset: fonts/PaybAck.ttf
    - family: MonoSpatial
      fonts:
        - asset: fonts/MonoSpatial.ttf
    - family: KC
      fonts:
        - asset: fonts/KenyanCoffee-Regular.ttf
  assets:
    - assets/imgs/basile_carre.png
    


